name: Telegram-Weather-Bot
on:
  schedule:
    - cron: "0 5 * * *"  
  workflow_dispatch:     
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script
        env:
        
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python main.py
